testando coverage no sonarcloud

diff --git a/.github/workflows/.gitlab-ci.yaml b/.github/workflows/.gitlab-ci.yaml
--- a/.github/workflows/.gitlab-ci.yaml
+++ b/.github/workflows/.gitlab-ci.yaml
@@ -101,15 +101,16 @@ jobs:
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
           SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
-          SONAR_PROJECT_TOKEN: ${{ secrets.SONAR_PROJECT_TOKEN }}
+          SONAR_PROJECT_KEY: ${{ secrets.SONAR_PROJECT_KEY }}
         run: ./gradlew sonar --info
-      - name: Check coverage
+      - name: Check SonarCloud Quality Gate
         run: |
-          COVERAGE=$(curl -s -u SONAR_TOKEN: "https://sonarcloud.io/api/measures/component?component=SONAR_PROJECT_TOKEN&metricKeys=coverage" | jq -r '.component.measures[0].value')
-          if (( $(echo "$COVERAGE < 80" | bc -l) )); then
-            echo "Coverage is below 80%. Current coverage: $COVERAGE%"
-            exit 1
-          fi
+          STATUS=$(curl -s -u "${{ secrets.SONAR_TOKEN }}:" "https://sonarcloud.io/api/qualitygates/project_status?projectKey=SONAR_PROJECT_KEY")
+           if [[ $(echo $STATUS | jq -r '.projectStatus.status') != "OK" ]]; then
+             echo "SonarCloud Quality Gate failed"
+             exit 1
+           fi
+
 
 
 
